/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

//npx openapi-typescript src/openapi/0.1-alpha.json --output src/openapi/test.d.ts

export interface paths {
  "/trees": {
    /** Returns all trees */
    get: {
      responses: {
        /** A list of pets. */
        200: {
          content: {
            "application/json": string;
          };
        };
      };
      
    };
  };
  "/tree": {
    /** Creates new Tree */
    post: operations["addTree"];
  };
  "/tree/{treeId}": {
    /** Returns tree based on ID */
    get: operations["getTreeById"];
  };
}

export interface components {
  schemas: {
    ErrorModel: {
      message: string;
      code: number;
    };
    /** Tree definition */
    tree: {
      id: string;
      location: components["schemas"]["location"];
      species: components["schemas"]["species"];
      /** Diameter in centimeter */
      dbh: number;
      /** Height in centimeter */
      height?: number;
      /** Diameter per height */
      trunk?: components["schemas"]["dimensions_trunk"];
      /** Diameter per height */
      crown?: components["schemas"]["dimensions_crown"];
      /** Birthday of the tree */
      birth?: string;
      /** List of absolute or relative path to file */
      image?: components["schemas"]["image"][];
    };
    /** Changes to the tree data */
    trees_history: {
      /** URL-friendly id */
      id: string;
      /** Date and time when change happened. */
      changedAt?: string;
      /** Tree state before manipulation. */
      definition: components["schemas"]["tree"];
      uId?: string;
    } & {
      changeAt: unknown;
    };
    new_area: components["schemas"]["location"][][][];
    /** Changes to the track data */
    area_history: {
      /** URL-friendly id */
      id?: string;
      /** Date and time when change happened. */
      changedAt?: string;
      /** Tree state before manipulation. */
      definition?: components["schemas"]["new_area"];
      uId?: string;
    };
    location: {
      coordinates: components["schemas"]["coordinates"];
      /** The decimal accuracy of coordinates in meter (2 decimal places max). */
      accuracy?: number;
    };
    /** Anchor point of the Object on a map. Array of longitude, latitude and [altitude] coordinate. Reference system: WGS84 Web Mercator with longitude and latitude units of decimal degrees. */
    coordinates: number[];
    /** Tree Species values taken from https://github.com/b-lack/tree-species */
    species: string;
    dimensions_trunk: components["schemas"]["diameter_height"][];
    dimensions_crown: components["schemas"]["diameter_height"][];
    /** Array including height and diameter at height */
    diameter_height: {
      /** Height of tree in PERCENT where diameter is measured */
      height?: number;
      /** Diameter in CENTIMETER at measured height */
      diameter?: number;
    };
    /** A universal resource identifier (URI), according to RFC3986. */
    image: string;
    /** Version of the used vinv schema, the file should be validated against */
    v: string;
    /** Once created, this ID should never change. */
    id: string;
    /** Date and time this document was created. */
    created: string;
    inventory: {
      /** List of individual tree definitions */
      treeList: components["schemas"]["tree"][];
      treeHistory?: components["schemas"]["trees_history"][];
    };
    areas: {
      /** List of logical area definitions */
      areaList?: components["schemas"]["new_area"][];
      areaHistory?: components["schemas"]["area_history"][];
    };
    /** List of functional extensions */
    extensions: { [key: string]: unknown };
  };
}

export interface operations {
  /** Creates new Tree */
  addTree: {
    responses: {
      /** Add Individual Tree. */
      200: {
        content: {
          "application/json": string;
        };
      };
      /** error payload */
      default: {
        content: {
          "application/json": components["schemas"]["ErrorModel"];
        };
      };
    };
  };
  /** Returns tree based on ID */
  getTreeById: {
    parameters: {
      path: {
        /** ID of tree to use */
        treeId: string;
      };
    };
    responses: {
      /** Individual Tree. */
      200: {
        content: {
          "application/json": components["schemas"]["tree"];
        };
      };
    };
  };
}

export interface external {}
