/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface schemas {
  /** Tree definition */
  tree: {
    id: string;
    location: location[""];
    species: species[""];
    /** Diameter in centimeter */
    dbh: number;
    /** Height in centimeter */
    height?: number;
    /** Diameter per height */
    trunk?: dimensions_trunk[""];
    /** Diameter per height */
    crown?: dimensions_crown[""];
    /** Birthday of the tree */
    birth?: string;
    /** List of absolute or relative path to file */
    image?: image[""][];
  };
  /** Changes to the tree data */
  trees_history: {
    /** URL-friendly id */
    id: string;
    /** Date and time when change happened. */
    changedAt?: string;
    /** Tree state before manipulation. */
    definition: tree[""];
    uId?: string;
  } & {
    changeAt: unknown;
  };
  new_area: location[""][][][];
  /** Changes to the track data */
  area_history: {
    /** URL-friendly id */
    id?: string;
    /** Date and time when change happened. */
    changedAt?: string;
    /** Tree state before manipulation. */
    definition?: new_area[""];
    uId?: string;
  };
  location: {
    coordinates: coordinates[""];
    /** The decimal accuracy of coordinates in meter (2 decimal places max). */
    accuracy?: number;
  };
  /** Anchor point of the Object on a map. Array of longitude, latitude and [altitude] coordinate. Reference system: WGS84 Web Mercator with longitude and latitude units of decimal degrees. */
  coordinates: number[];
  /** Tree Species values taken from https://github.com/b-lack/tree-species */
  species: string;
  dimensions_trunk: diameter_height[""][];
  dimensions_crown: diameter_height[""][];
  /** Array including height and diameter at height */
  diameter_height: {
    /** Height of tree in PERCENT where diameter is measured */
    height?: number;
    /** Diameter in CENTIMETER at measured height */
    diameter?: number;
  };
  /** A universal resource identifier (URI), according to RFC3986. */
  image: string;
  /** Version of the used vinv schema, the file should be validated against */
  v: string;
  /** Once created, this ID should never change. */
  id: string;
  /** Date and time this document was created. */
  created: string;
  inventory: {
    /** List of individual tree definitions */
    treeList: tree[""][];
    treeHistory?: trees_history[""][];
  };
  areas: {
    /** List of logical area definitions */
    areaList?: new_area[""][];
    areaHistory?: area_history[""][];
  };
  /** List of functional extensions */
  extensions: { [key: string]: unknown };
}

export interface external {}
