/**
 * 
 * vinv
 * 
 * 
 * Lightweight open data exchange standard for individual tree based forest management, visualisation & analytics.
 * 
 * Version: 0.1-alpha
 * Contact: support@vinv.io
 * Generated by OpenAPI Generator: https://openapi-generator.tech
 */

// package openapi3graphql-server

// tree_api

export default {
    Query: {

        // @return Tree
        GetTreeById: ($treeId) => {
            return {
                "treeId": "treeId_example"
            };
        },

    },

    Mutation: {

        // @return String!
        AddTree: () => {
            return {
                
            };
        },

    }
}